version: '3.8'

services:
  patent-researcher-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    volumes:
      - ../memory:/app/memory
      - ../output:/app/output
      - ../knowledge:/app/knowledge
      - ../mlartifacts:/app/mlartifacts
      - ../mlruns:/app/mlruns
      - ../logs:/app/logs
    restart: unless-stopped

  mlflow:
    image: python:3.11-slim
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install mlflow &&
               mlflow server --host 0.0.0.0 --port 5000"
    volumes:
      - ../mlruns:/mlruns
    restart: unless-stopped 